name: salah_tracker
description: Islamic Prayer Tracker App - Track your daily prayers with Jamaah, Adah, Qalah status
publish_to: 'none'
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Prayer Time Calculation
  adhan: ^2.0.0

  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

  # Location - Using manual selection for now
  # geolocator: ^11.0.0
  # geocoding: ^3.0.0

  # UI/Charts
  fl_chart: ^0.66.0
  table_calendar: ^3.0.9

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

  # Cupertino Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Modern Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-VariableFont_opsz,wght.ttf

  # Add custom notification sounds later
  # assets:
  #   - assets/sounds/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
