name: iOS Build Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ios:
    name: Build iOS App
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'

    - name: Flutter doctor
      run: flutter doctor -v

    - name: Get dependencies
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze
      continue-on-error: true

    - name: Generate iOS project files
      run: flutter create --platforms=ios .

    - name: Precache iOS artifacts
      run: flutter precache --ios

    - name: Disable code signing in Xcode project
      run: |
        # Modify iOS project to disable automatic signing
        sed -i '' 's/ENABLE_AUTOMATIC_SIGNING = YES/ENABLE_AUTOMATIC_SIGNING = NO/g' ios/Runner.xcodeproj/project.pbxproj || true
        sed -i '' 's/CODE_SIGN_STYLE = Automatic/CODE_SIGN_STYLE = Manual/g' ios/Runner.xcodeproj/project.pbxproj || true

    - name: Build iOS (unsigned)
      run: flutter build ios --release --no-codesign --no-tree-shake-icons
      env:
        FLUTTER_BUILD_MODE: release
        FLUTTER_SUPPRESS_ANALYTICS: true

    - name: Create IPA
      run: |
        mkdir -p Payload
        cp -r build/ios/iphoneos/Runner.app Payload/
        zip -r SalahTracker.ipa Payload
        rm -rf Payload

    - name: Upload unsigned IPA
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: SalahTracker-unsigned-ipa
        path: SalahTracker.ipa
        retention-days: 30
